name: Test Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Test Build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare for AARCH64 cross compilation
        run: |
          rustup target add aarch64-unknown-linux-gnu
          sudo apt-get install --yes gcc-aarch64-linux-gnu

      - name: Prepare versions file
        run:
          x86_64-linux-gnu-gcc --version | grep x86_64-linux-gnu-gcc > versions.txt
          aarch64-linux-gnu-gcc --version | grep aarch64-linux-gnu-gcc >> versions.txt
          rustc --version >> versions.txt
          cat versions.txt

      - name: Build Package (x86_64)
        run: |
          cargo build --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: -C linker=x86_64-linux-gnu-gcc

      - name: Build Package (aarch64)
        run: |
          cargo build --target aarch64-unknown-linux-gnu
        env:
          RUSTFLAGS: -C linker=aarch64-linux-gnu-gcc

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libraries
          path: |
            target/x86_64-unknown-linux-gnu/debug/libpq_rs_node.so
            target/aarch64-unknown-linux-gnu/debug/libpq_rs_node.so
            versions.txt
