name: Test Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Test Build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org
          node-version: 18.x

      - name: Build Package (native x86_64)
        run: |
          cargo build --target x86_64-unknown-linux-gnu

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binary x86_64
          path: target/x86_64-unknown-linux-gnu/debug/libpq_rs_node.so
